/* Biblioteca base. Cada hecho: c = categoría (cerebro, cuerpo, vida), t = título, b = cuerpo.
   Para agregar uno, copia un bloque {c:..., t:..., b:...} y pégalo antes del último ]. */
window.FACTS=[
 {c:"cerebro",t:"La cocaína gasta la dopamina que te hace disfrutar lo normal",b:"La cocaína bloquea la recaptación de dopamina, así que el cerebro queda inundado. Para defenderse, baja la cantidad de receptores de dopamina. Resultado: cuando no consumes, la comida, la música, el sexo y el trabajo se sienten planos. Eso que llamas 'perder el gusto por vivir' tiene nombre: anhedonia. Es reversible, pero toma semanas a meses de tiempo limpio, y cada recaída reinicia el reloj."},
 {c:"cerebro",t:"La psicosis por cocaína se vuelve más fácil de provocar con cada episodio",b:"Esto se llama sensibilización: el cerebro 'aprende' el camino hacia la paranoia y lo recorre más rápido. Por eso hoy te llega casi de inmediato algo que antes requería días. No es que la droga cambió: cambió tu cerebro. Y la falta de sueño le abre la puerta de par en par."},
 {c:"cerebro",t:"Oír voces o sentir que te siguen es un efecto conocido, no una locura",b:"Entre un 50 y un 90 por ciento de las personas que consumen cocaína de forma intensa reportan síntomas paranoides o alucinaciones en algún momento. Suele pasar al dormir. El riesgo real es cuando los episodios se repiten y se acercan: algunos estudios muestran que una parte de esas personas desarrolla un trastorno psicótico que ya no depende de la droga."},
 {c:"cerebro",t:"La cocaína envejece el cerebro más rápido",b:"Estudios con resonancia muestran que el consumo crónico reduce la materia gris en zonas de atención, memoria y control de impulsos, a un ritmo casi el doble que el envejecimiento normal. Parte se recupera con abstinencia, parte no."},
 {c:"cerebro",t:"La 'clarividencia' que sientes es el mismo efecto que la paranoia",b:"La cocaína sube la dopamina en el circuito que asigna importancia a las cosas. Todo parece significativo, conectado, revelador. Esa es la sensación de ver con claridad. Es exactamente el mismo mecanismo que te hace sentir que te siguen: el cerebro asignando importancia a cosas que no la tienen."},
 {c:"cerebro",t:"La depresión después de consumir no es casualidad",b:"El bajón de dopamina y serotonina que sigue al consumo produce un estado depresivo que puede durar días. En personas que ya tienen tendencia a la depresión, la cocaína la empeora y hace que los episodios sean más largos. Lo que describes, que te da depresión y no euforia, es lo que pasa cuando el cerebro ya no tiene de dónde sacar más."},
 {c:"cuerpo",t:"El riesgo de infarto se dispara justo después de consumir",b:"En la hora siguiente al consumo, el riesgo de infarto es muchas veces mayor que el normal, incluso en personas jóvenes y sin problemas al corazón. La cocaína aprieta las arterias, sube la presión y acelera el corazón al mismo tiempo. Es la causa más común de infarto en menores de 40 años en urgencias."},
 {c:"cuerpo",t:"Mezclar con alcohol crea una droga nueva, más tóxica",b:"Cuando hay cocaína y alcohol juntos, el hígado produce cocaetileno, una sustancia que dura más que la cocaína y es más dañina para el corazón. Es una de las combinaciones con más muertes súbitas."},
 {c:"cuerpo",t:"La cocaína que llega a Chile casi nunca viene sola",b:"Una parte muy grande de la cocaína en la calle está cortada con levamisol, un desparasitante para animales. El levamisol puede destruir glóbulos blancos (dejándote sin defensas) y causar vasculitis: heridas en la piel que no sanan, sobre todo en orejas, nariz y mejillas. No hay forma de saber cuánto lleva mirándola."},
 {c:"cuerpo",t:"La nariz se destruye por dentro",b:"Cada vez que aspiras, la cocaína corta el riego de sangre al tabique. Con el tiempo el cartílago muere y se perfora. La nariz que 'se moja sola' cuando hay ganas es el cuerpo anticipando la droga, igual que la saliva antes de comer."},
 {c:"cuerpo",t:"Las ganas de orinar y la deshidratación tienen explicación",b:"La cocaína estimula el sistema nervioso simpático y altera cómo los riñones manejan el agua. La urgencia urinaria que sientes es parte de eso. Sumado a que no comes ni tomas agua mientras consumes, el cuerpo termina el episodio deshidratado y con el azúcar por el suelo: de ahí los mareos y el antojo de dulces."},
 {c:"cuerpo",t:"Dormir mal multiplica todo",b:"Sin dormir, el cuerpo no limpia los residuos del cerebro ni recupera los niveles de dopamina. Por eso dos noches sin dormir con cocaína producen efectos que un consumo con sueño no produce. El sueño no es lo que falta: es parte del daño."},
 {c:"cuerpo",t:"Convulsiones y fiebre: el cuerpo se recalienta",b:"La cocaína sube la temperatura corporal y en dosis altas o repetidas puede provocar convulsiones, incluso en personas sin epilepsia. Una temperatura por sobre 40 grados después de consumir es una emergencia."},
 {c:"vida",t:"Las ganas duran 15 a 30 minutos, siempre",b:"Un deseo intenso de consumir funciona como una ola: sube, llega a un punto máximo y baja, aunque no hagas nada. Lo que lo alarga es pelear contra él o alimentarlo con planes. La técnica se llama 'surfear la ola' y es de las más probadas en tratamiento de adicciones."},
 {c:"vida",t:"El dinero que se va no es solo el de la droga",b:"A la plata que se gasta directo hay que sumar el día de trabajo perdido, la comida que no compraste, lo que pediste fiado y lo que dejaste de ahorrar. Un gasto de 60.000 pesos semanales son más de 3 millones al año solo en lo directo."},
 {c:"vida",t:"La recaída no borra lo avanzado",b:"La recuperación casi nunca es una línea recta. Lo que predice el éxito a largo plazo no es nunca recaer, sino cuánto demoras en volver a levantarte y qué aprendes de cada caída. Cada Día 0 que marcaste fue más rápido que el anterior."},
 {c:"vida",t:"Los primeros 90 días son los más difíciles por una razón física",b:"La anhedonia y las ganas más fuertes se concentran en los primeros tres meses, mientras el cerebro vuelve a fabricar receptores de dopamina. Después de ese punto, la mayoría de las personas describe que 'vuelve el color'. Es un plazo real, no una frase."},
 {c:"vida",t:"El aislamiento alimenta la adicción",b:"La cocaína engancha más en cerebros aburridos y solos. Las ratas en jaulas con otras ratas y cosas que hacer consumen mucho menos que las ratas aisladas, aunque tengan la droga disponible. Lo que llamas 'sanar primero y después conectar' puede estar al revés: conectar es parte de sanar."},
 {c:"vida",t:"Tener el contacto guardado es tener la decisión tomada",b:"La mayoría de las recaídas no son una decisión: son una secuencia de pasos pequeños donde cada uno parece inofensivo. Guardar el número es el primer paso. Borrarlo pone un obstáculo justo donde la ola está más alta."}
];

/* Hechos para otras sustancias. Campo s = id de la sustancia (los de arriba son de cocaína y se marcan al cargar). */
window.FACTS.forEach(f=>{ if(!f.s) f.s="cocaina"; });
window.FACTS.push(
 {s:"pasta-base",c:"cuerpo",t:"La pasta base quema por dentro",b:"Lo que se fuma trae restos de queroseno y ácido del proceso. Cada pipa es una quemadura química en garganta y pulmones. Por eso la tos, la voz ronca y el dolor al respirar aparecen en semanas, no en años."},
 {s:"pasta-base",c:"cerebro",t:"Dos minutos de subida, una hora de angustia",b:"El efecto dura menos que cualquier otra droga común. Lo que sigue es una angustia intensa que empuja a fumar otra vez. No es falta de voluntad: es un ciclo diseñado por la química para que no pares."},
 {s:"pasta-base",c:"vida",t:"El tratamiento residencial gratuito existe",b:"SENDA tiene programas residenciales sin costo para pasta base. Para esta sustancia, salir del entorno por un tiempo suele ser lo que mejor funciona, y la lista de espera se acorta llamando al 1412 y pidiendo evaluación."},
 {s:"alcohol",c:"cuerpo",t:"No existe una cantidad de alcohol que sea segura para el cáncer",b:"La OMS lo clasifica en el mismo grupo que el tabaco. El riesgo de cáncer de boca, esófago, hígado y mama sube desde el primer trago, aunque sea poco. Cada semana sin beber baja ese riesgo."},
 {s:"alcohol",c:"cerebro",t:"El alcohol alivia la ansiedad hoy y la empeora mañana",b:"Mientras estás bebiendo, el cerebro se calma. Al pasar el efecto, rebota: más ansiedad que antes. Por eso parece que 'necesitas' beber para estar tranquilo: estás tratando la ansiedad que el alcohol mismo creó."},
 {s:"alcohol",c:"vida",t:"Dejarlo de golpe puede ser peligroso si bebes mucho a diario",b:"Es de las pocas sustancias cuya abstinencia puede matar: convulsiones y delirium tremens entre las 48 y 72 horas. Si bebes mucho todos los días, se deja con apoyo médico. No es cobardía: es el protocolo."},
 {s:"marihuana",c:"cerebro",t:"La marihuana de hoy no es la de tus papás",b:"La concentración de THC se multiplicó en 20 años. Las variedades potentes se asocian a más crisis de pánico y, en personas con predisposición, a episodios psicóticos. 'Es natural' no significa 'es suave'."},
 {s:"marihuana",c:"cuerpo",t:"La abstinencia de marihuana existe y dura una o dos semanas",b:"Irritabilidad, insomnio, sueños muy vívidos, poco apetito. No es peligrosa, pero es real, y es la razón por la que mucha gente cree que 'no puede dormir sin fumar'. El sueño vuelve solo entre la segunda y la cuarta semana."},
 {s:"marihuana",c:"vida",t:"Fumar todos los días apaga la motivación de a poco",b:"No es un mito: el uso diario se asocia a menos energía para empezar cosas y menos disfrute de lo que antes gustaba. Lo bueno es que es de lo primero que vuelve al dejarla."},
 {s:"benzodiacepinas",c:"cuerpo",t:"Las benzodiacepinas se dejan bajando, nunca de golpe",b:"Si las usas todos los días, cortarlas de un día para otro puede provocar convulsiones. Es la excepción a todo lo demás: aquí 'de a poco' no es una opción, es la única forma segura, y se hace con un médico."},
 {s:"benzodiacepinas",c:"cerebro",t:"Las lagunas de memoria no son casualidad",b:"Las benzodiacepinas bloquean la formación de recuerdos nuevos mientras hacen efecto. Con uso prolongado, la memoria y la concentración se deterioran de forma que se nota en el trabajo y en las conversaciones."},
 {s:"benzodiacepinas",c:"vida",t:"La mezcla con alcohol mata durmiendo",b:"Los dos deprimen la respiración. Juntos, una persona puede dormirse y no despertar. Si alguien tomó las dos cosas y no reacciona, es una emergencia, aunque parezca que 'solo duerme'."},
 {s:"mdma",c:"cuerpo",t:"El riesgo principal del MDMA es el calor, no la droga en sí",b:"Bailar horas en un lugar cerrado sin descansar puede subir la temperatura corporal a niveles que dañan órganos. Las muertes por MDMA son casi siempre por golpe de calor o por sodio bajo, no por sobredosis directa."},
 {s:"mdma",c:"cerebro",t:"El bajón de los martes tiene explicación",b:"El MDMA vacía la serotonina del cerebro. Los dos o tres días siguientes el ánimo cae. Si se usa cada fin de semana, la serotonina no alcanza a recuperarse y la tristeza se vuelve permanente."},
 {s:"mdma",c:"vida",t:"La pastilla con el mismo logo no es la misma pastilla",b:"Dos pastillas idénticas pueden traer cantidades muy distintas, o traer otra cosa: metanfetamina, catinonas o PMA, que actúa lento y lleva a tomar más. Por eso existen los kits de prueba."},
 {s:"anfetaminas",c:"cerebro",t:"Sin dormir, cualquier cerebro entra en psicosis",b:"Después de dos o tres días sin dormir con estimulantes, aparecen la paranoia y las alucinaciones, incluso en personas sin ninguna condición previa. No es locura: es privación de sueño. Dormir es el tratamiento."},
 {s:"anfetaminas",c:"cuerpo",t:"La metanfetamina envejece el cuerpo en meses",b:"Dientes, piel, peso, corazón. El deterioro físico que con otras drogas toma años, con metanfetamina se nota en meses. Y gran parte se recupera al dejarla, si es a tiempo."},
 {s:"anfetaminas",c:"vida",t:"El 'ritalín para estudiar' también es esto",b:"El metilfenidato sin receta es una anfetamina. Sirve para pasar una noche, pero el uso regular trae insomnio, ansiedad y dependencia, y lo que se memoriza sin dormir se olvida rápido."},
 {s:"ketamina",c:"cuerpo",t:"La ketamina destruye la vejiga en silencio",b:"El uso frecuente inflama la vejiga hasta dejarla rígida: dolor, urgencia por orinar cada rato, sangre. Se llama cistitis por ketamina. Si se deja a tiempo, se recupera; si no, puede ser irreversible."},
 {s:"ketamina",c:"cerebro",t:"En el 'k-hole' no sientes el cuerpo, y eso es lo peligroso",b:"Caídas, quemaduras, ahogarse con el vómito. Las lesiones por ketamina casi nunca son por la droga en sí, sino por lo que pasa mientras no puedes moverte ni sentir dolor."},
 {s:"ketamina",c:"vida",t:"Lo que te vendieron como ketamina puede no serlo",b:"En Chile es el ingrediente principal del tusi, y a veces lo que se vende como 'K' es un análogo con efectos más largos e impredecibles. Sin análisis, no hay forma de saberlo."},
 {s:"tusi",c:"vida",t:"El tusi no tiene cocaína ni 2C-B",b:"A pesar del nombre, los análisis muestran ketamina, MDMA y cafeína con colorante rosado, en proporciones que cambian de bolsa en bolsa. Hasta 9 sustancias distintas en una muestra, según la OEA."},
 {s:"tusi",c:"cuerpo",t:"Con tusi, la misma cantidad puede ser suave hoy y peligrosa mañana",b:"Como la mezcla cambia, no hay forma de 'conocer tu dosis'. El riesgo no es solo cuánto, sino qué trae esta bolsa en particular."},
 {s:"tusi",c:"cerebro",t:"Mezcla de disociativo y estimulante: el cuerpo recibe órdenes opuestas",b:"La ketamina baja y el MDMA sube. El corazón y la temperatura quedan en medio de dos señales contradictorias. Con alcohol encima, es de las combinaciones más riesgosas de la noche."},
 {s:"opioides",c:"cuerpo",t:"La sobredosis de opioides mata porque se deja de respirar",b:"No es dolor ni convulsión: es que la respiración se hace lenta hasta parar. Labios azulados, pupilas muy pequeñas, no despierta. La naloxona lo revierte y no hace daño si no era opioide."},
 {s:"opioides",c:"cerebro",t:"El tramadol también es un opioide",b:"En Chile es el más común, muchas veces de receta. Produce dependencia física real y su abstinencia es dura. Mezclado con alcohol o benzodiacepinas, el riesgo respiratorio es el mismo que con cualquier opioide."},
 {s:"opioides",c:"vida",t:"Existe tratamiento médico para la abstinencia",b:"La abstinencia de opioides es muy dolorosa pero tiene tratamiento: medicamentos que la hacen manejable y, en dependencia fuerte, terapia de sustitución. Se pide en el consultorio o por el 1412."},
 {s:"tabaco",c:"cuerpo",t:"La nicotina engancha más rápido que casi cualquier droga",b:"El cigarro llega al cerebro en 10 segundos y el efecto dura minutos. Ese ciclo corto es lo que lo hace tan difícil de dejar, no la 'falta de voluntad'."},
 {s:"tabaco",c:"vida",t:"Dejar primero la otra sustancia y después el tabaco es una decisión válida",b:"Mucha gente en recuperación fuma más al principio. Priorizar no es rendirse. Cuando llegue el momento, los parches y chicles de nicotina duplican la probabilidad de lograrlo."},
 {s:"tabaco",c:"cerebro",t:"La ansiedad que 'calma' el cigarro es la que el cigarro creó",b:"Entre un cigarro y otro, la nicotina baja y aparece inquietud. Fumar la quita. Parece que te calma, pero está apagando una ansiedad que no tendrías sin fumar. A las 3 semanas sin nicotina, esa inquietud desaparece."}
);

/* El bajón y lo que viene después: aplica a todas las sustancias (s:"general") */
window.FACTS.push(
 {s:"general",c:"cerebro",t:"El bajón: por qué después de consumir todo se siente peor",b:"Cualquier droga que sube el ánimo de golpe lo hace gastando la dopamina o la serotonina que el cerebro tenía guardada. Cuando pasa el efecto, el cerebro queda en deuda: tristeza, irritabilidad, cansancio, nada entusiasma. Eso es el bajón. Dura de uno a varios días según la sustancia, y es la razón principal por la que la gente vuelve a consumir: para tapar el bajón que el consumo mismo creó."},
 {s:"general",c:"cerebro",t:"Anhedonia: cuando nada da gusto",b:"Es la incapacidad de disfrutar lo que antes gustaba: la comida, la música, la gente. Aparece porque el cerebro bajó sus receptores de dopamina para defenderse de las subidas artificiales. Se siente como depresión, pero tiene una diferencia importante: mejora sola con tiempo limpio, normalmente entre el mes y los tres meses. Saberlo ayuda a no rendirse en la semana dos."},
 {s:"general",c:"cerebro",t:"Distimia: la tristeza de fondo que dura años",b:"La distimia (hoy llamada trastorno depresivo persistente) es un ánimo bajo casi todos los días durante dos años o más, menos intenso que una depresión mayor pero constante. Mucha gente consume justamente para 'salir' de ese estado, y el consumo lo empeora. Si llevas meses limpio y el ánimo sigue plano, no es que la recuperación 'no funcione': puede ser distimia, y tiene tratamiento (terapia y a veces medicamentos). Vale la pena consultarlo con un médico."},
 {s:"general",c:"cerebro",t:"Depresión y consumo se alimentan entre sí",b:"Las personas con depresión tienen más probabilidad de consumir, y el consumo produce o empeora la depresión. Por eso tratar solo una de las dos cosas suele fallar. Lo que mejor funciona es abordar las dos a la vez: dejar la sustancia y, en paralelo, tratar el ánimo con un profesional."},
 {s:"general",c:"vida",t:"Cómo se siente la recuperación, semana a semana",b:"Semana 1: cansancio, hambre, sueño o insomnio, ganas fuertes. Semanas 2 a 4: el cuerpo mejora pero el ánimo cae; es cuando más gente recae, porque 'ya no se siente mejor'. Mes 2 y 3: vuelve el gusto por cosas pequeñas, el sueño se ordena. Después del mes 3: la mayoría describe que 'vuelve el color'. No es lineal, pero la dirección es esa."}
);
