/* Biblioteca base. Cada hecho: c = categoría (cerebro, cuerpo, vida), t = título, b = cuerpo.
   Para agregar uno, copia un bloque {c:..., t:..., b:...} y pégalo antes del último ]. */
window.FACTS=[
 {c:"cerebro",t:"La cocaína gasta la dopamina que te hace disfrutar lo normal",b:"La cocaína bloquea la recaptación de dopamina, así que el cerebro queda inundado. Para defenderse, baja la cantidad de receptores de dopamina. Resultado: cuando no consumes, la comida, la música, el sexo y el trabajo se sienten planos. Eso que llamas 'perder el gusto por vivir' tiene nombre: anhedonia. Es reversible, pero toma semanas a meses de tiempo limpio, y cada recaída reinicia el reloj."},
 {c:"cerebro",t:"La psicosis por cocaína se vuelve más fácil de provocar con cada episodio",b:"Esto se llama sensibilización: el cerebro 'aprende' el camino hacia la paranoia y lo recorre más rápido. Por eso hoy te llega casi de inmediato algo que antes requería días. No es que la droga cambió: cambió tu cerebro. Y la falta de sueño le abre la puerta de par en par."},
 {c:"cerebro",t:"Oír voces o sentir que te siguen es un efecto conocido, no una locura",b:"Entre un 50 y un 90 por ciento de las personas que consumen cocaína de forma intensa reportan síntomas paranoides o alucinaciones en algún momento. Suele pasar al dormir. El riesgo real es cuando los episodios se repiten y se acercan: algunos estudios muestran que una parte de esas personas desarrolla un trastorno psicótico que ya no depende de la droga."},
 {c:"cerebro",t:"La cocaína envejece el cerebro más rápido",b:"Estudios con resonancia muestran que el consumo crónico reduce la materia gris en zonas de atención, memoria y control de impulsos, a un ritmo casi el doble que el envejecimiento normal. Parte se recupera con abstinencia, parte no."},
 {c:"cerebro",t:"La 'clarividencia' que sientes es el mismo efecto que la paranoia",b:"La cocaína sube la dopamina en el circuito que asigna importancia a las cosas. Todo parece significativo, conectado, revelador. Esa es la sensación de ver con claridad. Es exactamente el mismo mecanismo que te hace sentir que te siguen: el cerebro asignando importancia a cosas que no la tienen."},
 {c:"cerebro",t:"La depresión después de consumir no es casualidad",b:"El bajón de dopamina y serotonina que sigue al consumo produce un estado depresivo que puede durar días. En personas que ya tienen tendencia a la depresión, la cocaína la empeora y hace que los episodios sean más largos. Lo que describes, que te da depresión y no euforia, es lo que pasa cuando el cerebro ya no tiene de dónde sacar más."},
 {c:"cuerpo",t:"El riesgo de infarto se dispara justo después de consumir",b:"En la hora siguiente al consumo, el riesgo de infarto es muchas veces mayor que el normal, incluso en personas jóvenes y sin problemas al corazón. La cocaína aprieta las arterias, sube la presión y acelera el corazón al mismo tiempo. Es la causa más común de infarto en menores de 40 años en urgencias."},
 {c:"cuerpo",t:"Mezclar con alcohol crea una droga nueva, más tóxica",b:"Cuando hay cocaína y alcohol juntos, el hígado produce cocaetileno, una sustancia que dura más que la cocaína y es más dañina para el corazón. Es una de las combinaciones con más muertes súbitas."},
 {c:"cuerpo",t:"La cocaína que llega a Chile casi nunca viene sola",b:"Una parte muy grande de la cocaína en la calle está cortada con levamisol, un desparasitante para animales. El levamisol puede destruir glóbulos blancos (dejándote sin defensas) y causar vasculitis: heridas en la piel que no sanan, sobre todo en orejas, nariz y mejillas. No hay forma de saber cuánto lleva mirándola."},
 {c:"cuerpo",t:"La nariz se destruye por dentro",b:"Cada vez que aspiras, la cocaína corta el riego de sangre al tabique. Con el tiempo el cartílago muere y se perfora. La nariz que 'se moja sola' cuando hay ganas es el cuerpo anticipando la droga, igual que la saliva antes de comer."},
 {c:"cuerpo",t:"Las ganas de orinar y la deshidratación tienen explicación",b:"La cocaína estimula el sistema nervioso simpático y altera cómo los riñones manejan el agua. La urgencia urinaria que sientes es parte de eso. Sumado a que no comes ni tomas agua mientras consumes, el cuerpo termina el episodio deshidratado y con el azúcar por el suelo: de ahí los mareos y el antojo de dulces."},
 {c:"cuerpo",t:"Dormir mal multiplica todo",b:"Sin dormir, el cuerpo no limpia los residuos del cerebro ni recupera los niveles de dopamina. Por eso dos noches sin dormir con cocaína producen efectos que un consumo con sueño no produce. El sueño no es lo que falta: es parte del daño."},
 {c:"cuerpo",t:"Convulsiones y fiebre: el cuerpo se recalienta",b:"La cocaína sube la temperatura corporal y en dosis altas o repetidas puede provocar convulsiones, incluso en personas sin epilepsia. Una temperatura por sobre 40 grados después de consumir es una emergencia."},
 {c:"vida",t:"Las ganas duran 15 a 30 minutos, siempre",b:"Un deseo intenso de consumir funciona como una ola: sube, llega a un punto máximo y baja, aunque no hagas nada. Lo que lo alarga es pelear contra él o alimentarlo con planes. La técnica se llama 'surfear la ola' y es de las más probadas en tratamiento de adicciones."},
 {c:"vida",t:"El dinero que se va no es solo el de la droga",b:"A la plata que se gasta directo hay que sumar el día de trabajo perdido, la comida que no compraste, lo que pediste fiado y lo que dejaste de ahorrar. Un gasto de 60.000 pesos semanales son más de 3 millones al año solo en lo directo."},
 {c:"vida",t:"La recaída no borra lo avanzado",b:"La recuperación casi nunca es una línea recta. Lo que predice el éxito a largo plazo no es nunca recaer, sino cuánto demoras en volver a levantarte y qué aprendes de cada caída. Cada Día 0 que marcaste fue más rápido que el anterior."},
 {c:"vida",t:"Los primeros 90 días son los más difíciles por una razón física",b:"La anhedonia y las ganas más fuertes se concentran en los primeros tres meses, mientras el cerebro vuelve a fabricar receptores de dopamina. Después de ese punto, la mayoría de las personas describe que 'vuelve el color'. Es un plazo real, no una frase."},
 {c:"vida",t:"El aislamiento alimenta la adicción",b:"La cocaína engancha más en cerebros aburridos y solos. Las ratas en jaulas con otras ratas y cosas que hacer consumen mucho menos que las ratas aisladas, aunque tengan la droga disponible. Lo que llamas 'sanar primero y después conectar' puede estar al revés: conectar es parte de sanar."},
 {c:"vida",t:"Tener el contacto guardado es tener la decisión tomada",b:"La mayoría de las recaídas no son una decisión: son una secuencia de pasos pequeños donde cada uno parece inofensivo. Guardar el número es el primer paso. Borrarlo pone un obstáculo justo donde la ola está más alta."}
];
