/* Reconocer qué tomó alguien, mirando sin preguntar. Para cuidar, no para juzgar: saber qué consumió
   alguien es lo primero que pregunta el 131 y lo que decide qué hacer si se pone mal.
   Cada entrada: id (de la guía), nombre, cuerpo[] (señales físicas), conducta[] (cómo actúa), dosCaras (la misma droga, dos reacciones),
   alarma (cuándo deja de ser "está volado" y pasa a ser emergencia). Sin cantidades ni formas de uso. */
window.SENALES=[
{id:"cocaina",nombre:"Cocaína",cuerpo:["Pupilas grandes, incluso con luz.","Mandíbula apretada, muecas, se muerde los labios.","Se toca o se aprieta la nariz, aspira seguido, a veces le gotea.","Va al baño mucho, en grupo o de a dos.","No come, no tiene sed, suda aunque no baile."],conducta:["Habla rápido, mucho y encima de los demás.","Confianza y energía que no tenía hace una hora.","Impaciencia: no termina lo que empieza, cambia de tema.","Cada 30 o 40 minutos se 'apaga' y vuelve a desaparecer un rato."],dosCaras:"Una persona se vuelve el alma de la fiesta; otra se pone paranoica, mira la puerta, cree que hablan de ella. Las dos consumieron lo mismo. Pesan el sueño que traía, cuánto lleva, si mezcló con alcohol y cómo es su ansiedad de base.",alarma:"Dolor en el pecho, pulso que no baja al sentarse, confusión, o paranoia con agresividad."},
{id:"pasta-base",nombre:"Pasta base",cuerpo:["Labios o dedos quemados, olor químico en la ropa.","Delgadez marcada, ojeras, descuido en semanas.","Inquietud: no puede quedarse sentado."],conducta:["Ciclo corto: minutos de euforia y después angustia visible.","Busca más de inmediato; pide plata, se va y vuelve.","Desconfianza, mira alrededor, se irrita rápido."],dosCaras:"Al principio parece solo 'acelerado'; con el uso seguido aparece la angustia y la paranoia como estado permanente. Lo que cambia no es la persona: es el tiempo de consumo.",alarma:"Dolor en el pecho, convulsiones, o paranoia con riesgo para sí mismo o para otros."},
{id:"alcohol",nombre:"Alcohol",cuerpo:["Olor.","Habla arrastrada, se repite.","Camina inestable, se apoya, se le caen cosas.","Ojos rojos y caídos, cara enrojecida."],conducta:["Desinhibido: más cariñoso, más ruidoso o más agresivo que de costumbre.","Lentitud para entender y responder.","Lagunas: no recuerda lo que dijo hace un rato."],dosCaras:"Hay quien se ríe de todo y quien pelea con todos. La misma cantidad hace cosas distintas según cuánto comió, cuánto pesa, qué ánimo traía y cuánta tolerancia tiene. El 'borracho feliz' y el 'borracho agresivo' no son dos drogas: son dos personas.",alarma:"No despierta, respira lento, vomita estando dormido, piel fría. No se 'duerme la mona' sola."},
{id:"marihuana",nombre:"Marihuana",cuerpo:["Ojos rojos, párpados caídos.","Boca seca, hambre repentina.","Olor en la ropa o el pelo.","Lentitud en movimientos y reacciones."],conducta:["Risa fácil, se queda pegado en una idea o en una canción.","Habla menos o divaga.","Tiempo distorsionado: 'hace cuánto llegamos'."],dosCaras:"Para una persona es relajo y risa; para otra, al rato, es ansiedad, silencio y sensación de que la miran. Influyen la potencia (hay variedades mucho más fuertes), la experiencia, el ánimo previo y la predisposición a la ansiedad. 'Ser de paz' con marihuana no es garantía de nada: la misma persona puede tener la otra cara otro día.",alarma:"Crisis de pánico que no cede en una hora, vómitos repetidos, o si se sospecha un sintético: convulsiones, pulso disparado."},
{id:"benzodiacepinas",nombre:"Benzodiacepinas",cuerpo:["Parece borracho pero no huele a alcohol.","Ojos entrecerrados, cabeceo.","Habla lenta y pastosa, descoordinación."],conducta:["Calma excesiva, desinterés, se queda dormido en cualquier parte.","Lagunas de memoria completas.","A veces desinhibición rara, sin euforia."],dosCaras:"Una persona se relaja y se duerme; otra, sobre todo si mezcló con alcohol, hace cosas de las que no se acordará. La diferencia la hace la mezcla y la tolerancia.",alarma:"Respiración lenta, no despierta, labios azulados, sobre todo si también bebió."},
{id:"mdma",nombre:"MDMA (éxtasis)",cuerpo:["Pupilas muy grandes.","Mandíbula apretada, muele los dientes, masca chicle sin parar.","Suda mucho, piel caliente, no para de bailar.","Movimientos rápidos de ojos, escalofríos."],conducta:["Cariño con todo el mundo, abrazos, 'te quiero mucho' a desconocidos.","Habla de emociones, muy sensible a la música y al tacto.","No siente cansancio aunque lleve horas."],dosCaras:"Para unos es amor universal; para otros, ansiedad y mandíbula sin poder hablar. Depende de lo que traía la pastilla (muchas veces no es MDMA), del calor del lugar y de cuánto descansó.",alarma:"Piel muy caliente y dejó de sudar, confusión, convulsiones, o dolor de cabeza fuerte tras tomar mucha agua."},
{id:"anfetaminas",nombre:"Anfetaminas y metanfetamina",cuerpo:["Pupilas grandes, mirada fija.","No duerme, no come, pierde peso en días.","Se rasca, se toca la cara, mueve la boca.","Con metanfetamina: deterioro visible de dientes y piel."],conducta:["Energía y charla sin fin, horas.","Hace tareas repetitivas con obsesión (ordenar, desarmar cosas).","Después de días: irritable, paranoico, oye cosas."],dosCaras:"El primer día es productividad y confianza; al tercer día sin dormir es psicosis. No es otra persona: es la misma sin sueño.",alarma:"Varios días sin dormir con confusión, temperatura alta, convulsiones, agitación extrema."},
{id:"ketamina",nombre:"Ketamina",cuerpo:["Camina como en cámara lenta, se tambalea, choca con cosas.","Mirada perdida, 'ausente'.","Habla lenta, incoherente.","No reacciona al dolor (se golpea y no se queja)."],conducta:["Se queda quieto mirando un punto.","Pierde el hilo a mitad de la frase.","En un 'k-hole' no responde aunque esté con los ojos abiertos."],dosCaras:"Un poco parece borrachera suave; un poco más y la persona desaparece dentro de sí misma. La línea entre las dos es más fina de lo que la gente cree, y con alcohol se borra.",alarma:"No responde y vomita, o respira lento (sobre todo con alcohol)."},
{id:"tusi",nombre:"Tusi",cuerpo:["Mezcla de señales de MDMA (pupilas, mandíbula, calor) y de ketamina (tambaleo, mirada perdida).","Polvo rosado en la nariz, el teléfono o la tarjeta."],conducta:["Euforia y cariño que de pronto se vuelven desconexión y silencio.","Muy variable de una persona a otra en la misma noche, porque cada bolsa es distinta."],dosCaras:"Dos personas que compartieron la misma bolsa pueden estar en estados opuestos: una bailando, otra sentada sin poder hablar. El tusi no es una sustancia, es una mezcla, y a cada cuerpo le pega la parte que le pega.",alarma:"Las mismas de MDMA (calor extremo) y de ketamina (no responde)."},
{id:"opioides",nombre:"Opioides",cuerpo:["Pupilas muy pequeñas, como puntos, incluso en la oscuridad.","Cabeceo: se duerme sentado y despierta a ratos.","Se rasca, habla lenta, párpados pesados.","Respiración lenta."],conducta:["Calma total, desinterés por lo que pasa alrededor.","Náuseas, vómitos sin parecer borracho."],dosCaras:"Para quien tiene tolerancia, parece solo somnoliento; para quien no, la misma cantidad puede parar la respiración. Por eso una pastilla 'de un amigo' que a él no le hace nada puede ser mortal para otro.",alarma:"Respiración muy lenta, labios azulados, no despierta. Naloxona si hay, y 131."},
{id:"lsd",nombre:"LSD y hongos",cuerpo:["Pupilas grandes.","Fascinación con luces, texturas, su propia mano.","Risa sin motivo o, al revés, cara de susto."],conducta:["Habla de cosas que ve o siente que los demás no.","Pierde la noción del tiempo.","Puede pasar de la risa al pánico en minutos."],dosCaras:"El mismo cartón: una persona tiene la mejor noche de su vida y otra un mal viaje de seis horas. Lo que decide es el ánimo con que llegó, el lugar, la compañía, y si era LSD de verdad o un NBOMe.",alarma:"Convulsiones, temperatura alta, pulso disparado (puede no ser LSD), o pánico que no cede con compañía tranquila."},
{id:"ghb",nombre:"GHB / GBL",cuerpo:["Parece muy borracho pero no huele a alcohol.","Pasa de estar bien a dormido de golpe.","Náuseas, movimientos bruscos, a veces convulsiones."],conducta:["Desinhibición sexual marcada.","Se 'apaga' en minutos."],dosCaras:"Unas gotas de más separan el estar relajado de estar inconsciente. No hay versión segura con alcohol.",alarma:"Se duerme y no despierta, respira lento. De lado, no sola, 131."}
];

/* Por qué la misma droga le pega distinto a cada persona */
window.FACTORES=[
{t:"Cuánto y qué tan puro",b:"La misma 'raya' o 'pepa' puede tener el doble o la mitad de sustancia que la de ayer. Nadie lo sabe mirándola."},
{t:"Con qué se mezcló",b:"Alcohol encima de casi cualquier cosa cambia el efecto y multiplica el riesgo. Dos sustancias no suman: se multiplican."},
{t:"Cuánto durmió y comió",b:"Sin sueño, los estimulantes llevan a la paranoia. Sin comida, el alcohol pega el doble."},
{t:"Con qué ánimo llegó",b:"Lo que traes adentro se amplifica. Ansiedad previa más estimulante es paranoia; tristeza previa más alcohol es llanto o pelea."},
{t:"Dónde y con quién",b:"Un lugar cerrado y caluroso convierte el MDMA en golpe de calor. Gente desconocida convierte la marihuana en paranoia."},
{t:"Tolerancia",b:"Lo que a un consumidor habitual 'no le hace nada' puede ser una sobredosis para alguien que empieza. Compartir dosis entre distintos es la forma más común de que alguien termine en urgencias."},
{t:"El cuerpo de cada uno",b:"Peso, sexo, metabolismo, medicamentos que toma (antidepresivos y MDMA son una mala mezcla) y enfermedades que no sabe que tiene (del corazón, sobre todo)."},
{t:"Salud mental de base",b:"Predisposición a la ansiedad, a la depresión o a la psicosis: la sustancia no las crea de la nada, pero las puede encender."}
];
